blank_issues_enabled: false
contact_links:
  - name: Adventure Issues
    url: https://github.com/KyoriPowered/adventure/issues/new/choose
    about: MiniMessage issues have been migrated to the main Adventure repository.
